name: build-checkstyle
on: [push, pull_request]

jobs:
  build-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup JDK 8
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 8

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Run Build
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build

      - name: Run Checkstyle
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: checkstyle
