name: build-checkstyle
on: [push, pull_request]

jobs:
  build-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Build and Tests
        run: ./gradlew clean build

      - name: Run Checkstyle
        run: ./gradlew checkstyle
