name: tag-release-publish
on: workflow_dispatch

permissions:
  contents: write

jobs:
  tag-release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true

      - name: Run Build and Tests
        run: ./gradlew clean build

      - name: Get version from build.gradle.kts
        run: |
          version_regex='version = "([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)"'
          if [[ `cat build.gradle.kts` =~ $version_regex ]]; then
            version="${BASH_REMATCH[1]}" && echo "Found version: $version"
            echo "version=$version" >> $GITHUB_ENV
            echo "tag=v$version" >> $GITHUB_ENV
          else
            echo "Didn't find version in build.gradle.kts" && exit 1
          fi

      - name: Publish to Maven Central
        # After VALIDATED, Maven Central automatically publishes the deployment, which may take another 10-30 minutes
        run: ./gradlew publishAndReleaseToMavenCentral -PmavenCentralDeploymentValidation=VALIDATED
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Set Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Create tag
        run: git tag -m "${{ env.tag }}" "${{ env.tag }}" && git push origin "${{ env.tag }}"

      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag }}
          files: build/libs/allpairs4j-${{ env.version }}.jar
