name: tag-release-publish
on: workflow_dispatch

jobs:
  tag-release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup JDK 8
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 8

      - name: Run Build
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build

      - name: Get version from build.gradle.kts
        run: |
          version_regex='version = "([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)"'
          if [[ `cat build.gradle.kts` =~ $version_regex ]]; then
            version="${BASH_REMATCH[1]}" && echo "Found version: $version"
            echo "version=$version" >> $GITHUB_ENV
            echo "tag=v$version" >> $GITHUB_ENV
          else
            echo "Didn't find version in build.gradle.kts" && exit 1
          fi

      - name: Set Git user
        run: |
          git config --global user.email "pavelnazimok@gmail.com"
          git config --global user.name "pavelicii"

      - name: Create tag
        run: git tag -m ${{ env.tag }} ${{ env.tag }} && git push origin ${{ env.tag }}

      - name: Release to GitHub
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ env.tag }}
          files: build/libs/allpairs4j-${{ env.version }}.jar

      - name: Publish to Sonatype
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_PASSWORD }}
